const CALENDAE_LOCALS = {
  AR: { value: 'ar', label: 'العربية' },
  BG: { value: 'bg', label: 'български език' },
  CA: { value: 'ca', label: 'Català' },
  CS: { value: 'cs', label: 'Čeština' },
  DA: { value: 'da', label: 'Dansk' },
  DE: { value: 'de', label: 'Deutsch' },
  EN_GB: { value: 'en-gb', label: 'English (UK)' },
  EN_US: { value: 'en-us', label: 'English (US)' },
  EO: { value: 'eo', label: 'Esperanto' },
  ES: { value: 'es', label: 'Español' },
  FA_IR: { value: 'fa-ir', label: 'فارسی' },
  FI: { value: 'fi', label: 'Suomi' },
  FR: { value: 'fr', label: 'Français' },
  GN: { value: 'gn', label: 'Avañe\'ẽ' },
  HE: { value: 'he', label: 'עברית' },
  HR: { value: 'hr', label: 'Hrvatski jezik' },
  HU: { value: 'hu', label: 'Magyar' },
  ID: { value: 'id', label: 'Bahasa Indonesia' },
  IT: { value: 'it', label: 'Italiano' },
  JA: { value: 'ja', label: '日本語 (にほんご)' },
  KM: { value: 'km', label: 'ខ្មែរ' },
  KO_KR: { value: 'ko-kr', label: '한국어' },
  LU: { value: 'lu', label: 'Kiluba' },
  LV: { value: 'lv', label: 'Latviešu valoda' },
  ML: { value: 'ml', label: 'മലയാളം' },
  MS: { value: 'ms', label: 'Bahasa Melayu' },
  NB_NO: { value: 'nb-no', label: 'Norsk' },
  NL: { value: 'nl', label: 'Nederlands' },
  PL: { value: 'pl', label: 'Polski' },
  PT_BR: { value: 'pt-br', label: 'Português (BR)' },
  PT: { value: 'pt', label: 'Português' },
  RO: { value: 'ro', label: 'Română' },
  RU: { value: 'ru', label: 'русский' },
  SK: { value: 'sk', label: 'Slovenčina' },
  SL: { value: 'sl', label: 'Slovenski Jezik' },
  SR: { value: 'sr', label: 'српски језик' },
  SV: { value: 'sv', label: 'Svenska' },
  TA: { value: 'ta', label: 'தமிழ்' },
  TH: { value: 'th', label: 'ไทย' },
  TR: { value: 'tr', label: 'Türkçe' },
  UK: { value: 'uk', label: 'Українська' },
  VI: { value: 'vi', label: 'Tiếng Việt' },
  ZH_HANS: { value: 'zh-hans', label: '中文(简体)' },
  ZH_HANT: { value: 'zh-hant', label: '中文(繁體)' }
}
export const getAsArr = () => {
  return Object.keys(CALENDAE_LOCALS).map(key => CALENDAE_LOCALS[key])
}
export default CALENDAE_LOCALS
